### ISSUE TITLE
Zen Mode: Trigger as soon as user begins typing

### ISSUE THREAD

**Issue by orschiro** [classeur/classeur#146]
Currently, the Zen Mode is being triggered after 5 seconds of typing without moving the mouse. 

From a user perspective, it would be more intuitive if Zen Mode is being toggled as soon as the user starts typing.

**Comment by benweet** [comment]
Thanks @orschiro :)

**Comment by orschiro** [comment]
With pleasure. :-)

**Comment by VillageHubertChen** [comment]
Thank @orschiro , I finally could turn it on :-)

I began writing the Missing Manual for Classeur. This is what I have for Zen Mode. Can you comment it? There is also a question in there. Could you guys answer it?

---

### What is Zen Mode

Zen is about you being in the _Zone_ as in writing so focused that you forget anything else but your writing. Classeur assists you in entering the _Zone_ via the _Zen Mode_ which will fade the Classeur UI so all what is left for you to see: Is your writing!

### How to turn on Zen Mode:
1. Click Menu, enable the "Zen Mode" button 
2. Turn off Side Preview (if it is on, Zen Mode is disabled)
3. Turn off Side Bar (if it is on, Zen Mode is disabled)
4. Start typing without using the mouse
5. Wait for 5 seconds (during which you can type or not after you began typing)
6. Zen Mode will turn on automatically, by fading out the UI

### Limitations

I am using Classeur over any other text editor because I need the productivity of Live Preview and Live Table of Contents when typing markdown. Ironically turning on these functions turns off Zen Mode. I am contacting the authors to learn if I may have misunderstood the concept or if they will enable Zen Mode during writing with Preview / ToC enabled?

# Comment
1. I LIKE this feature!
2. If you were allow Zen Mode while Preview and / or ToC is one it would be intuitive to use. As it is I tried for half hour and could not turn it on, unless I found your writing today and did more testing. And even now I must choose between Zen Mode or Life Preview. I am sad that I have to choose :-(

**Comment by orschiro** [comment]
@VillageHubertChen thank you for your crisp tutorial! Would you agree if we post it on our FAQ [1]?

You actually gave me another idea. Maybe switching to Zen Mode could automatically switch of Side Preview and Side Bar? 

Regarding your ToC and Life Preview comment, I see Zen Mode as the most minimalist environment you can think of. Thus I tend to favour it not be enabled when using ToC and Life Preview. @benweet what do you think?

[1] https://classeur.zendesk.com/hc/en-us/sections/201884219-FAQ

**Comment by sbrl** [comment]
If you've got the side preview enabled, I don't think it makes sense to turn it
off automatically.

**Comment by VillageHubertChen** [comment]
@orschiro 

You are most welcome :-)

## Agree to use in your FAQ ...

... however, I suggest you wait until this feature is finalized and I adopted my writing to your final implementation. I will post it in here when ready.

## Conditional Zen View is a Pain

If you look at my writing on how to turn on Zen View it is 6 steps. This is way too complicated for mere mortals. 

## Make Zen View Real Simple

I suggest a real simple implementation with it's manual reads like this:
1. Click Menu, enable the "Zen Mode" button 

## How I would use Zen Mode with Preview

To me it very useful. I like your implementation as is. Begin typing and your UI dims. Move the mouse and your UI shows again. Just do the same when Preview and Side Pane are enable. I would use it like so:

### Writing

During writing I am in the zone. Dim everything else other than the writing pane.

### Reviewing

I move the mouse, all else fades to visible instantly. During reviewing I am not in the zone and in fact live preview and Table of Contents is most useful

### Return writing

I just start writing and all else fades out. I get back into the zone.

## Let me know what you think ...

... or ask any questions you have.

**Comment by orschiro** [comment]
Thank you Hubert! 

Let's see what we can do to make this a smoother experience. :smiley: 

~Robert

**Comment by VillageHubertChen** [comment]
You are welcome! Good luck! ~Hubert

**Comment by benweet** [comment]
Should be fixed in v1.7.0.

**Comment by VillageHubertChen** [comment]
Dear Ben,

I though you like to know that it works very well. I like how you remain it dimmed when using the mouse over the writing pane, while you turn it on completely when moving the mouse over to the preview pane. Nice touch!

Thank you!

**Comment by orschiro** [comment]
Glad you like it and thanks for the feedback, Hubert! :-)

**Comment by VillageHubertChen** [comment]
You are very welcome :-)
