### ISSUE TITLE
Request: Free Premium for students?

### ISSUE THREAD

**Issue by fredcallaway** [classeur/classeur#22]
Shot in the dark here, but GitHub does it, so I thought I'd ask. I'm a student at Cornell University and I'd love to use this app because collaborative projects are the one thing that forces me away from markdown. With this slick user interface--and critically, real time collaboration--I think I could talk my friends into switching over from Google Drive. But there is absolutely no chance they'll pay $5 a month for it.

This would be not only a charitable act, but also a good business move. You will sacrifice almost no revenue because very few students would ever subscribe to such a service. And it's great publicity in the demographic that will become your target audience in 1 to 4 years: tech-savvy professionals. If this app actually takes all the best from Google Drive and StackEdit, I would certainly request that future employers buy business licenses.

*_crosses fingers_*

**Comment by benweet** [comment]
Hi @fredcallaway,

Thanks for your interest in Classeur.

At the moment, real time collaboration is for premium user only, I don't know any easy way to offer premium accounts for free to students. The pricing model may change in the futur though as Classeur is still in beta.

Note that you can still have other people contributing to a file without real time collaboration. When you finish your edits, just drag your file in a public folder shared by your collaborator, it will change the ownership of the file so that your collaborator can work on it.

I hope it helps.
